version: '3.7'

services:
  nginx:
    image: nginx:1.18.0
    volumes:
      - ./logs:/var/log/nginx
    ports:
      - "80:80"

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yaml
      - ./logs:/var/log/nginx
    command: ["-config.file=/etc/promtail/config.yaml"]

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafanadata:/var/lib/grafana

  loki:
    image: grafana/loki:3.5.2
    ports:
      - "3100:3100"

volumes:
  grafanadata: {}